### ISSUE TITLE
Import error with Python 3.7

### ISSUE THREAD

**Issue by nottug** [Waultics/coinmarketcap-history#17]
When trying to import `cmc`, I get the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/cmc/__init__.py", line 2
    from .async import async_utils
              ^
SyntaxError: invalid syntax
```

This happened with another library as well, it seems no modules can be called `async` in Python 3.7.

Here's some context:

https://github.com/ccxt/ccxt/issues/3376

**Comment by axano** [comment]
same problem here, I fixed id by replacing the async keyword with async_var where it was used as a variable and async_folder when it was used as an import. Works like a charm. Another solution would be to change the interpreter to python 3.6 or something else as python 3.7 uses async as a keyword but this is not a proper solution.

**Comment by nazariyv** [comment]
the previous owner of the repo found this guy @Alescontrela to maintain the library, but I can see he is not maintaining it. @Alescontrela do you want to delegate the maintenance to someone else?

**Comment by escontra** [comment]
Hi,

Sorry for the lack of response for the past couple of months, i've had other activities take my attention away from this repository. I will be taking a look at current issues and make proper changes. 

@nazariyv In addition to maintenance, I restructured the whole repository and changed some of its functionality, which is why some issues have become apparent. If you, or anybody would like to help improve the robustness of cmc, please feel free to contribute :) all PRs will be considered.
